apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
      - name: nginx-deployment-2
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 30m
            memory: 70Mi
          limits:
            cpu: 250m
            memory: 300Mi